// import type { Metadata } from 'next';
// export const metadata: Metadata = {
//   title: 'Blog',
//   description: 'Generated by create next app',
// };
interface Props {
  params: { id: string };
}
export async function generateMetadata({ params }: Props) {
  const { id } = await params;
  return {
    title: `Blog Detail ${id}`,
  };
}
export default async function BlogDetail({ params }: Props) {
  const { id } = await params;
  const data = await fetch(`http://localhost:3000/api/article?test=123`);
  const posts = await data.json();
  return (
    <div>
      <h1>BlogDetail</h1>
      <div>{id}</div>
      <div>--- GET ---</div>
      <div>{posts.age}</div>
      <div>{posts.name}</div>
      <div>{posts.url}</div>
    </div>
  );
}
